// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjdjlylicfnbjyrgqlyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZGpseWxpY2ZuYmp5cmdxbHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTg3ODcsImV4cCI6MjA2OTQ3NDc4N30.KCz3nC-R4qjMC2NIS7ITz7UEbOV-2iqwNc7sNupiikk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});